---
name: ğŸ  Home Assistant CI

# yamllint disable-line rule:truthy
on:
  workflow_run:
    workflows:
      - 'ğŸ§¹âœ¨ Linting & Style Checks'
    types: [completed]

jobs:
  home-assistant:
    name: ğŸ§ª Home Assistant Core Config Check (${{ matrix.version }})
    # needs: [yamllint]
    if: |
      github.repository == 'saya6k/home-assistant-config' &&
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.name == 'ğŸ§¹âœ¨ Linting & Style Checks' &&
      github.event.workflow_run.head_branch == 'main' &&
      github.event.workflow_run.event == 'push'
    runs-on: ubuntu-latest
    concurrency:
      group: release-pages
      cancel-in-progress: false
    strategy:
      matrix:
        version: ['stable', 'beta', 'dev']
    steps:
      - name: â¤µï¸ Check out repository
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          fetch-depth: 0

      - name: ğŸ“¥ Clone custom component - OpenID Connect for Home Assistant
        run: |
          git clone https://github.com/christiaangoossens/hass-oidc-auth.git
          mv -v hass-oidc-auth/custom_components/* custom_components

      - name: ğŸš€ Validate Home Assistant Configuration
        uses: frenck/action-home-assistant@v1.4.1
        with:
          path: '.'
          secrets: ./secrets.fake.yaml
          version: ${{ matrix.version }}
