---
name: ğŸ  Home Assistant CI

# yamllint disable-line rule:truthy
on:
  workflow_run:
    workflows:
      - 'ğŸª„ Refresh Repository Badges'
      - 'ğŸ§¹âœ¨ Linting & Style Checks'
    types: [completed]

jobs:
  home-assistant:
    name: ğŸ§ª Home Assistant Core Config Check ('${matrix.version}')
    # needs: [yamllint]
    if: |
      github.repository == 'saya6k/home-assistant-config' &&
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.name == 'ğŸ§¹âœ¨ Linting & Style Checks'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['stable', 'beta', 'dev']
    steps:
      - name: â¤µï¸ Check out repository
        uses: actions/checkout@v5
        with:
          ref: '${github.event.workflow_run.head_sha}'

      - name: ğŸ“¥ Clone custom component - OpenID Connect for Home Assistant
        run: |
          git clone https://github.com/christiaangoossens/hass-oidc-auth.git
          mv -v hass-oidc-auth/custom_components/* custom_components

      - name: ğŸš€ Validate Home Assistant Configuration
        uses: frenck/action-home-assistant@v1.4.1
        with:
          path: '.'
          secrets: ./secrets.fake.yaml
          version: '${matrix.version}'

  esphome:
    name: ğŸ”Œ ESPHome Configuration Check
    runs-on: ubuntu-latest
    # needs: [yamllint]
    steps:
      - name: â¤µï¸ Check out repository
        uses: actions/checkout@v5
        with:
          ref: '${github.event.workflow_run.head_sha}'

      - name: ğŸ Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: ğŸ“¦ Install ESPHome dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install esphome
          pip list
          esphome version

      - name: ğŸ—ï¸ Copy secrets stub into ESPHome folder
        run: cp ./secrets.fake.yaml ./esphome/secrets.yaml

      - name: ğŸ” Validate ESPHome configuration files
        # yamllint disable rule:line-length
        run: |
          for file in $(find ./config/esphome -type f -name "*.yaml" -maxdepth 1 -not -name "secrets.yaml"); do
            esphome "${file}" config
          done
