---
name: ðŸ§¹âœ¨ Linting & Style Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  yamllint:
    name: ðŸ§¹ YAML Lint
    runs-on: ubuntu-latest
    steps:
      - name: â¤µï¸ Checkout Repository
        uses: actions/checkout@v5

      - name: ðŸš€ Run yamllint
        uses: frenck/action-yamllint@v1.5.0

  remarklint:
    name: ðŸ“ Markdown Lint
    runs-on: ubuntu-latest
    steps:
      - name: â¤µï¸ Checkout Repository (main branch)
        uses: actions/checkout@v5
        with:
          ref: main

      - name: ðŸ§ Run Remark Lint
        uses: docker://pipelinecomponents/remark-lint:latest
        continue-on-error: true
        with:
          args: >
            remark --no-stdout --color --frail --use preset-lint-recommended docs/**/*.md
