---
name: ğŸª„ Refresh Repository Badges

on:
  schedule:
    - cron: '0 0 * * *'  # â° Run daily at 00:00 UTC
  push:
    branches:
      - main

jobs:
  refresh:
    name: ğŸ”„ Update Badges
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ·ï¸ Refresh badges for Home Assistant config
        uses: b3b00/refreshBadgesAction@v1.0.7
        with:
          repository: 'saya6k/home-assistant-config'
          branch: 'main'
